IF DB_ID('MEL_EEL_Automation_Dev') IS NULL
BEGIN
	CREATE DATABASE MEL_EEL_Automation_Dev;

END
GO

ALTER DATABASE MEL_EEL_Automation_Dev SET RECOVERY SIMPLE;
ALTER DATABASE MEL_EEL_Automation_Dev SET ANSI_NULLS ON, QUOTED_IDENTIFIER ON;
ALTER DATABASE MEL_EEL_Automation_Dev SET READ_COMMITTED_SNAPSHOT ON;
GO
